### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by flexchar** [GoogleCloudPlatform/nfs-server-docker#5]
I see this image being referenced in multiple places. I am exploring option to use it as well. Is there any documentation on how one set up the exports?

At the moment I am building the image from reverse reading the Dockerfile/entrypoint

Findings:

This repo seems to be coming from https://github.com/kubernetes/kubernetes/tree/master/test/images/volume/nfs
And that seems to be based of https://github.com/cpuguy83/docker-nfs-server

So use this by passing your exports as arguments to image's entrypoint.

**Comment by cgn170** [comment]
You can find an example about how to use this docker image in another yaml definition in this repo, please check the following link

https://github.com/GoogleCloudPlatform/click-to-deploy/blob/5c7523aefa0318aadaf3f4b1f809564d335fed85/k8s/elastic-gke-logging/scripts/backup-nfs.yaml#L19
